services:
  php:
    env_file:
      - .env
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
      target: frankenphp_dev
    #depends_on:
    #  - boilerplate-database
    #image: ${IMAGES_PREFIX:-}boilerplate-app
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
    volumes:
      - ./.:/app
      - caddy_data:/data
      - caddy_config:/config
    ports:
        # HTTP
        - target: 80
          published: ${HTTP_PORT:-80}
          protocol: tcp
        # HTTPS
        - target: 443
          published: ${HTTPS_PORT:-443}
          protocol: tcp
        # HTTP/3
        - target: 443
          published: ${HTTP3_PORT:-443}
          protocol: udp

volumes:
  #database_data:
  caddy_data:
  caddy_config: